### PR TITLE
🔥  added markup support

### PR DESCRIPTION
**Pull request by msalbrain**
## Description

Pr for #33 added editor.vue components to right places and made html display on product pages

### CODE REVIEW

**Comment by shurco** [comment]
I see several problems:
1. The editing block is attached to the previous block and it is not clear what can be edited in it. I suggest adding indents, adding a separator before the buttons, and trying to highlight the editing field somehow.
2. The editing field contains formatted text, but it is not displayed on the actual website. It is necessary to add formatting styles in the website's CSS as well.

admin
site

**Comment by msalbrain** [comment]
Oh 
Thought I added the styling for the main site, will check it out and the other problem

**Comment by msalbrain** [comment]
I added a placeholder to make it clear where to type in the inputs. 

image

image




and the description on the site has formatting, i added that in the first pr 
image

**Comment by msalbrain** [comment]
and also added design for description in site

image

**Comment by shurco** [comment]
Looks cool!

**Pull request merged**
